services:
  tests:
    image: ghcr.io/axelpal/sellerstore-laravel-app:${GITHUB_REF_SLUG:-local}
    tty: true
    entrypoint: ""
    command: ./artisan test
    depends_on:
      - pgsql
      - redis
  phpstan:
    image: ghcr.io/axelpal/sellerstore-laravel-app:${GITHUB_REF_SLUG:-local}
    tty: true
    entrypoint: ""
    command: ./vendor/bin/phpstan analyse .
    depends_on:
      - pgsql
      - redis
  app:
    image: ghcr.io/axelpal/sellerstore-laravel-app:${GITHUB_REF_SLUG:-local}
    tty: true
    entrypoint: /wait-for pgsql:5432 -t 60 -- /app-entrypoint.sh
    depends_on:
      - pgsql
      - redis
  nginx:
    image: ghcr.io/axelpal/sellerstore-laravel-nginx:${GITHUB_REF_SLUG:-local}
    depends_on:
      - app
  redis:
    image: redis
  pgsql:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sellerstore
      POSTGRES_HOST_AUTH_METHOD: trust
