version: "3.3"
services:
  app:
    image: ghcr.io/axelpal/sellerstore-laravel-app:${IMAGE_TAG:-latest}
    env_file: .env
    restart: always
    tty: true
    entrypoint: /wait-for mysql:5432 -t 60 -- /app-entrypoint.sh
    command: php-fpm -R -F
    environment:
      STARTUP_START_SUPERVISORD: "true"
      STARTUP_START_CONSUMERS: "true"
      STARTUP_START_CRON: "true"
      DEFAULT_WORKERS_COUNT: 2
    extra_hosts:
      - "mysql:172.17.0.1"
      - "redis:172.17.0.1"
    volumes:
      - .env:/app/.env:delegated

  nginx:
    image: ghcr.io/axelpal/sellerstore-laravel-nginx:${IMAGE_TAG:-latest}
    env_file: .env
    restart: always
    tty: true
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SECURE_PORT}:80
    depends_on:
      - app